### PR TITLE
Fixes for ParseException handling

### LINKED ISSUE #17: Diktat-demo silently handles illegal syntax
It should be an error

### PR DESCRIPTION
**Pull request by petertrr**
Closes #17

### CODE REVIEW

File: src/jvmMain/kotlin/org/cqfn/diktat/demo/controller/DemoController.kt [hunk 1]
```diff
@@ -48,19 +49,21 @@ class DemoController {
...
                 codeFix.check(file.absolutePath)
             }
-        } catch (e: ParseException) {
-            codeForm.warnings = listOf(e.toString())
         }
-        codeForm.warnings = codeFix.listOfWarnings
-                .map { "Warn (${it.line}:${it.col}) ${it.detail}" }
-                .map { it.replace(file.absolutePath, "\"example_file_name\"") }
+        when {
+            result.isSuccess -> codeForm.warnings = codeFix.listOfWarnings
```
Comment (akuleshov7) [inline src/jvmMain/kotlin/org/cqfn/diktat/demo/controller/DemoController.kt:61]: move formatting to some method pls if possible

**Review by akuleshov7 — APPROVED** [review]
lgtm

File: src/jvmMain/kotlin/org/cqfn/diktat/demo/controller/DemoController.kt (hunk 1 above)
Comment (petertrr) [reply src/jvmMain/kotlin/org/cqfn/diktat/demo/controller/DemoController.kt]: Done
