### PR TITLE
Display execution errors

### LINKED ISSUE #19: RuleExecutionException is silently ignored, no results are show on UI

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Changed controller

Closes #19

### CODE REVIEW

File: src/jvmMain/kotlin/org/cqfn/diktat/demo/controller/DemoController.kt [hunk 1]
```diff
@@ -49,7 +50,15 @@ class DemoController {
         when {
             result.isSuccess -> codeForm.warnings = codeFix.listOfWarnings.map { it.prettyFormat(file) }
             result.exceptionOrNull() is ParseException -> codeForm.warnings = listOf(result.exceptionOrNull().toString())
-            else -> log.error("Running formatter returned unexpected exception", result.exceptionOrNull())
+            else -> {
+                val issueLink = if (RulesSetTypes.KTLINT in codeForm.ruleSet) "https://github.com/pinterest/ktlint/issues" else "https://github.com/cqfn/diktat/issues"
+                codeForm.warnings = listOf(
+                    """
+                        |Unhandled exception during tool execution, please create a ticket at $issueLink:
+                        |${result.exceptionOrNull()!!.stackTraceToString()}
```
Comment (akuleshov7) [inline src/jvmMain/kotlin/org/cqfn/diktat/demo/controller/DemoController.kt:58]: please limit to 10 lines

**Review by akuleshov7 — APPROVED** [review]
lgtm
